---
pentest_core_packages:
  - nmap
  - netcat
  - socat
  - tcpdump
  - wireshark-cli
  - ffuf
  - gobuster
  - john
  - hashcat
  - hydra

pentest_optional_packages: []

feroxbuster_asset_name: aarch64-linux-feroxbuster.zip
nikto_asset_name: nikto-main.zip
sqlmap_repo_url: https://github.com/sqlmapproject/sqlmap.git
sqlmap_repo_ref: master
metasploit_enable: true
metasploit_snap_package: metasploit-framework
burp_download_url: https://portswigger-cdn.net/burp/releases/download?product=community&type=Jar
burp_install_dir: /opt/burp
burp_jar_path: /opt/burp/burpsuite_community.jar
searchsploit_repo_url: https://gitlab.com/exploit-database/exploitdb.git
searchsploit_install_dir: /opt/exploit-database
seclists_zip_url: https://github.com/danielmiessler/SecLists/archive/master.zip
rockyou_download_url: https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt
