---
- name: Configure pentest tooling
  hosts: pentest_core
  become: true
  roles:
    - role: pentest_core_tools
      tags: [tools]

- name: Configure vpn tooling
  hosts: vpn_clients
  become: true
  roles:
    - role: vpn_lab
      tags: [vpn]
